### ISSUE TITLE
Enabled attribute shouldn't be mandatory

### ISSUE THREAD

**Issue by kipusoep** [Alain-es/BackofficeTweaking#1]
I was just reading the documentation on our umbraco.
It states that the Enabled attribute is mandatory. Why is it mandatory?
I'd say every entry is enabled by default, unless you explicitely set Enabled to false.

**Comment by Alain-es** [comment]
Good point. Already changed in the version 0.2.0 (still need to update the documentation on our Umbraco). Thanks.
